import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.7'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.openapi.generator' version '7.12.0'

    // Version calculator
    id "com.github.gradle-git-version-calculator" version "1.1.0"
}

sourceSets {
    main {
        java.srcDir "$buildDir/generated/src/main/java"
    }
}

group = 'com.anonymous'
version = '0.0.1-SNAPSHOT'
description = 'finoana-api'

java {
    group = 'com.anonymous.finoanaapi'

    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.flywaydb:flyway-core'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.testcontainers:testcontainers:2.0.3'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:postgresql'
    implementation 'org.postgresql:postgresql'
    implementation 'org.flywaydb:flyway-database-postgresql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'net.datafaker:datafaker:2.5.2'
    implementation "org.openapitools:jackson-databind-nullable:0.2.6"

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // Spring security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'

    // Firebase
    implementation 'com.google.firebase:firebase-admin:9.2.0'
}

tasks.named('test') {
    useJUnitPlatform()
}

openApiGenerate {
    generatorName = "java"
    inputSpec = "$rootDir/doc/api.yml".toString()
    outputDir = "$buildDir/generated".toString()
    apiPackage = "com.anonymous.finoanaapi.controllers.api"
    invokerPackage = "com.anonymous.finoanaapi.controllers.client"
    modelPackage = "com.anonymous.finoanaapi.controllers.model"

    configOptions = [
            serializableModel: "true",
            serializationLibrary: "jackson",
            dateLibrary: "custom"
    ]
    typeMappings = [
            Date: "java.time.LocalDate",
            DateTime: "java.time.Instant",
    ]
    library = "native"

    groupId = 'com.anonymous'
    id = 'finoanaapi'
    skipValidateSpec = false
    logToStderr = true
    generateAliasAsModel = false
    enablePostProcessFile = false
    version = "0.1.0"
}

tasks.register('openApiGenerateTs', GenerateTask) {
    generatorName = "typescript-axios"

    inputSpec = "$rootDir/doc/api.yml"
    outputDir = "$buildDir/generated-ts"

    additionalProperties = [
            npmName: "@Finoana-App/finoana-api-client",
            npmVersion: project.version.toString(),

            supportsES6: "true",
            withSeparateModelsAndApi: "true",
            apiPackage: "api",
            modelPackage: "models",

            npmDependencies: "{ \"axios\": \"^1.6.0\" }"
    ]
}
